### ISSUE TITLE
Restrictive type for x (independent variable) and y components (state vector)

### ISSUE THREAD

**Issue by pekpuglia** [srenevey/ode-solvers#20]
I am currently working on a simulation project using this crate and [egaku](https://github.com/tiby312/egaku2d). I need to retrieve frame delta-times from egaku, and receive `f32`'s. I must then convert back and forth between `f32` and `f64`. It is a bit annoying, unsafe and inefficient. I believe there would also be demand for some more flexible typing in other parts of this otherwise great crate. Would it be too hard to allow for `f64` storage types? I believe it may be a simple matter of adding some generics.

**Comment by DarthB** [comment]
I have a similar issue with plotters.

**Comment by DarthB** [comment]
If that's in the spirit of the maintainers I would also look into this when working on [Move Instead Copy via From Trait](https://github.com/srenevey/ode-solvers/issues/23)

**Comment by srenevey** [comment]
I'm open to the suggestion, having more flexibility for the type would be good. If @DarthB wants to work on this as part of his other suggestion that would be great.
