### ISSUE TITLE
Is it possible to use this library with highter than 1D matricies

### ISSUE THREAD

**Issue by Adam-Ladd** [srenevey/ode-solvers#30]
Hi, could you please let me know if it is possible to use this library with higher than 1D matrices. I'm trying to solve the heat equation in 2D and can't find any way to do that with this library. 

If it is not possible could you please recommend any suitable libraries or advice me on any issues I might encounter should I attempt to write the code to suitably extend this library.

Thanks

**Comment by srenevey** [comment]
Hi,
I'm not sure I understand your question. The examples [here](https://srenevey.github.io/ode-solvers/examples/kepler_orbit.html) are three dimensional. If you are asking if the crates can solve Partial Differential Equations (PDEs) then the answer is no.

**Comment by Adam-Ladd** [comment]
Yes sorry I was being a little thick I've been loosely following a python course and they used the `scipy.integrate.solve_ivp` function for both ODE's and the heat equation, so I was trying to do the same with ode-solvers forgetting the heat equation is a PDE (as a side note the python course might also be doing it wrong as the doc's say that `solve_ivp` should only be used for ode's https://docs.scipy.org/doc/scipy/tutorial/integrate.html).

Out of interest so far I've only been working on ODE's computationally, are you able to recommend any good resources to check out for how to computationally solve PDE's and/or  any good crates for working on those problems. 

Thanks, and apologies for the mix up.
