### ISSUE TITLE
Version on crates.io is 2PR's out of date please update it to the latest version 

### ISSUE THREAD

**Issue by Adam-Ladd** [srenevey/ode-solvers#31]
The current version of this crate on crates.io is out of date compared to the version on github, most significantly the dependencies for several crates are out of date which recently caused me to waste an few hour debugging a program after checking the cargo.toml file here on github for which version of `nalgebra` to use with this crate. The version here on github lists `nalgebra = 0.33` in the `cargo.toml` file whereas the outdated version on crates.io (0.4.0) uses `nalgebra` version `0.32.6`

going by the date of the latest release of crates.io ( 0.4.0 last updated 9mo ago) the version on github appears to be that from PR #27 which means that the version there is 2PR's behind the version on github (at time of writing PR #29 was the last merged). Please can you update the version on crates.io to bring it up to date

**Comment by srenevey** [comment]
Published version `0.5.0`.

**Comment by Adam-Ladd** [comment]
Thanks
