### ISSUE TITLE
strange lines

### ISSUE THREAD

**Issue by burrbull** [srenevey/ode-solvers#5]
This check is always `true` as `dim` is number of equations:
https://github.com/srenevey/ode-solvers/blob/13fddcd5f2d23278c6e3474b56f780390315d211/src/dopri5.rs#L396

This is always `0.`:
https://github.com/srenevey/ode-solvers/blob/13fddcd5f2d23278c6e3474b56f780390315d211/src/dopri5.rs#L372

**Comment by srenevey** [comment]
Thanks for pointing this out.
