### ISSUE TITLE
Stiffness appears to be checked almost every timestep?

### ISSUE THREAD

**Issue by joshburkart** [srenevey/ode-solvers#9]
Hello -- thanks for providing this package!

I was trying to turn off stiffness detection and just let the solver use lots of tiny steps when necessary. I was thus going to set `n_stiff` to `u32::MAX`. However, even after doing this I found that `IntegrationError::StiffnessDetected` could still be returned. I traced it to this line in both `dop853.rs` and `dopri5.rs` -- shouldn't it be `self.stats.accepted_steps % self.n_stiff == 0` instead?

```rust
                if (self.stats.accepted_steps % self.n_stiff != 0) || iasti > 0 {
```

**Comment by srenevey** [comment]
Thank you for pointing this out. I have fixed it in the latest revision.
